# Test

In [2]:
import numpy as np

In [3]:
a=np.array([(1,2,4,6),(15,24,43,52),(12,244,453,53)])

In [4]:
a.ndim

2

In [5]:
a.itemsize

4

In [6]:
a.shape

(3, 4)

In [7]:
b=a.reshape(2,6)
b

array([[  1,   2,   4,   6,  15,  24],
       [ 43,  52,  12, 244, 453,  53]])

In [8]:
b[1,3]

244

In [9]:
a.max()

453

In [10]:
b.min()

1

In [11]:
b.mean()

75.75

In [12]:
c=np.array([(12,32,44,65),(515,245,463,522),(112,2424,4543,453)])
np.vstack((a,c))

array([[   1,    2,    4,    6],
       [  15,   24,   43,   52],
       [  12,  244,  453,   53],
       [  12,   32,   44,   65],
       [ 515,  245,  463,  522],
       [ 112, 2424, 4543,  453]])

In [13]:
np.hstack((a,c))

array([[   1,    2,    4,    6,   12,   32,   44,   65],
       [  15,   24,   43,   52,  515,  245,  463,  522],
       [  12,  244,  453,   53,  112, 2424, 4543,  453]])